spring:
  application:
    name: agenda
    version: 1.1.0
    author:
      name: Pedro Carara
      email : cararax@gmail.com

  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

rabbitmq:
  host: localhost
  port: '15672'
  username: guest
  password: guest

  result:
    exchange: result.exchange
    queue: result.queue
    routingkey: result.routingkey

