spring:
  application:
    name: agenda
    version: 1.0.0
    author:
      name: Pedro Carara
      email : cararax@gmail.com

server:
  port: 8081

rabbitmq:
  host: localhost
  port: '15672'
  username: guest
  password: guest

  result:
    exchange: result.exchange
    queue: result.queue
    routingkey: result.routingkey

